### ISSUE TITLE
Suffocation 

### ISSUE THREAD

**Issue by mrpwes** [Muqsit/Wilderness#3]
put miny maxy for anti suffocation

**Comment by Muqsit** [comment]
https://github.com/Muqsit/Wilderness/blob/master/resources/config.yml#L24

**Comment by Muqsit** [comment]
I've seen many wilderness plugins have that feature but a random Y value between min and max doesn't solve the issue of suffocation.

If you had a custom generator that generated hills and plains, ravines and floating lands, a randomized Y value is not going to help. It is infact going to cause even more serious problems like falling to your death.

The main feature this plugin offers is that **there's no need for servers to specify a Y range**, it takes care of that mess itself by for empty chunks to be filled before calculating the highest safest block and teleporting the player above it, instead of directly teleporting them.
